/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InvokeLocalExecutor {
  /**
   * Current working directory
   */
  cwd?: string;
  /**
   * Turn off colors in CLI output
   */
  "no-colors"?: boolean;
  /**
   * Serverless configuration file name, Default: serverless.ts
   */
  "serverless-file-ext"?: "ts" | "js" | "yml" | "json";
  /**
   * region where the service should be deployed
   */
  region?: string;
  /**
   * AWS profile to use for deployment, Default: default
   */
  "aws-profile"?: string;
  /**
   * Serverless app name
   */
  app?: string;
  /**
   * Serverless organization name
   */
  org?: string;
  /**
   * Use local credentials instead of AWS_PROFILE
   */
  "use-local-credentials"?: boolean;
  /**
   * Path to serverless configuration file
   */
  config?: string;
  /**
   * Stage to deploy to
   */
  stage?: string;
  /**
   * Parameter to override in serverless configuration file
   */
  param?: string;
  /**
   * Shows this message and quits
   */
  help?: boolean;
  /**
   * Shows version information and quits
   */
  version?: boolean;
  /**
   * Shows verbose output
   */
  verbose?: boolean;
  /**
   * Shows debug output
   */
  debug?: boolean;
  /**
   * Name of the function
   */
  function?: string;
  /**
   * Path to JSON or YAML file holding input data
   */
  path?: string;
  /**
   * input data
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * Flag to pass input data as a raw string
   */
  raw?: boolean;
  /**
   * Context of the service
   */
  context?: {
    [k: string]: unknown;
  };
  /**
   * Path to JSON or YAML file holding context data
   */
  contextPath?: string;
  /**
   * Override environment variables. e.g. --env VAR1=val1 --env VAR2=val2
   */
  env?: {
    [k: string]: unknown;
  };
  /**
   * Flag to turn on docker use for node/python/ruby/java
   */
  docker?: boolean;
  /**
   * Arguments to docker run command. e.g. --docker-arg "-p 9229:9229"
   */
  "docker-arg"?: string;
  [k: string]: unknown;
}
