/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LogsExecutor {
  /**
   * Current working directory
   */
  cwd?: string;
  /**
   * Turn off colors in CLI output
   */
  "no-colors"?: boolean;
  /**
   * Serverless configuration file name, Default: serverless.ts
   */
  "serverless-file-ext"?: "ts" | "js" | "yml" | "json";
  /**
   * region where the service should be deployed
   */
  region?: string;
  /**
   * AWS profile to use for deployment, Default: default
   */
  "aws-profile"?: string;
  /**
   * Serverless app name
   */
  app?: string;
  /**
   * Serverless organization name
   */
  org?: string;
  /**
   * Use local credentials instead of AWS_PROFILE
   */
  "use-local-credentials"?: boolean;
  /**
   * Path to serverless configuration file
   */
  config?: string;
  /**
   * Stage to deploy to
   */
  stage?: string;
  /**
   * Parameter to override in serverless configuration file
   */
  param?: string;
  /**
   * Shows this message and quits
   */
  help?: boolean;
  /**
   * Shows version information and quits
   */
  version?: boolean;
  /**
   * Shows verbose output
   */
  verbose?: boolean;
  /**
   * Shows debug output
   */
  debug?: boolean;
  /**
   * The function name
   */
  function?: string;
  /**
   * Tail the log output
   */
  tail?: boolean;
  /**
   * Logs before this time will not be displayed. Default: `10m` (last 10 minutes logs only)
   */
  startTime?: string;
  /**
   * A filter pattern
   */
  filter?: string;
  /**
   * Tail polling interval in milliseconds. Default: `1000`
   */
  interval?: number;
  [k: string]: unknown;
}
